const FETCH_DOCUMENT_REQUEST = "DOCUMENT/FETCH_DOCUMENT_REQUEST";
const FETCH_DOCUMENT_SUCCESS = "DOCUMENT/FETCH_DOCUMENT_SUCCESS";
const SAVE_DOCUMENT_SUCCESS = "DOCUMENT/SAVE_DOCUMENT_SUCCESS";

export { FETCH_DOCUMENT_REQUEST, FETCH_DOCUMENT_SUCCESS, SAVE_DOCUMENT_SUCCESS };
