const LIST_SECTIONS_SUCCESS = "HEADER/LIST_SECTIONS_SUCCESS";
const LIST_DOCUMENTS_SUCCESS = "HEADER/LIST_DOCUMENTS_SUCCESS";
const EDIT_SECTION_REQUEST = "HEADER/EDIT_SECTION_REQUEST";
const EDIT_SECTION_SUCCESS = "HEADER/EDIT_SECTION_SUCCESS";

export {
    LIST_DOCUMENTS_SUCCESS,
    LIST_SECTIONS_SUCCESS,
    EDIT_SECTION_REQUEST,
    EDIT_SECTION_SUCCESS
};
